from __future__ import annotations

MARKUP = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Monster Wrangler · Tier Bench</title>
<style>__MONSTER_STYLE__</style></head><body>
<div class="shell"><header class="topbar"><div class="brand"><div class="mark">⌁</div><div><h1>Monster Wrangler</h1><div class="sub" id="repoSub">Local evidence desk · loading</div></div></div><div class="actions"><div class="away"><span class="dot" id="awayDot"></span><span id="awayText">Safe to leave</span></div><button class="btn ghost" id="settingsBtn">Guardrails</button><button class="btn warn" id="pauseBtn">Pause after current</button><button class="btn danger" id="stopBtn">Emergency stop</button></div></header>
<section class="metrics"><div class="metric"><div class="label">Scheduler</div><div class="value" id="mScheduler">—</div></div><div class="metric"><div class="label">Running</div><div class="value" id="mRunning">0</div></div><div class="metric"><div class="label">Ready</div><div class="value" id="mReady">0</div></div><div class="metric"><div class="label">Blocked</div><div class="value" id="mBlocked">0</div></div><div class="metric"><div class="label">Accepted</div><div class="value" id="mAccepted">0</div></div><div class="metric"><div class="label">Verified yield</div><div class="value" id="mYield">—</div></div><div class="metric"><div class="label">Today</div><div class="value" id="mToday">$0.00 <span class="small" id="mTodayTasks">0 runs</span></div></div></section>
<main class="workspace"><section class="panel"><div class="panel-head"><div><h2 class="panel-title">Set the work</h2><div class="kicker">The repo keeps custody. You may leave.</div></div></div><form class="form" id="taskForm"><div class="field"><label>Title <span class="hint">human scan line</span></label><input id="title" maxlength="160" required placeholder="Harden port parsing"></div><div class="field"><label>Task <span class="hint">exact outcome</span></label><textarea id="task" required placeholder="Make parse_port reject values above 65535 without changing valid behavior."></textarea></div><div class="field"><label>Allowed files <span class="hint">one scope per line</span></label><textarea class="code" id="files" required placeholder="src/net.py&#10;tests/test_net.py"></textarea></div><div class="field"><label>Frozen acceptance <span class="hint">outside the model</span></label><textarea class="code" id="acceptance" required placeholder="python -m pytest tests/test_net.py -q"></textarea></div><div class="row"><div class="field"><label>Cartridge</label><select id="arm"><option>arm_b</option><option>arm_a</option><option>arm_c</option></select></div><div class="field"><label>Priority</label><input id="priority" type="number" min="0" max="100" value="50"></div></div><div class="field"><label>Depends on <span class="hint">task IDs</span></label><input class="code" id="depends" placeholder="mw-abc123, mw-def456"></div><div class="field"><label>Backend manifest <span class="hint">inside repo</span></label><input class="code" id="manifest" value="pilot_backends.json"></div><label class="check"><input id="queueNow" type="checkbox" checked><span>Arm immediately when dependencies are accepted.</span></label><label class="check"><input id="approvalRequired" type="checkbox"><span>Require a separate explicit arm action.</span></label><div class="safety"><strong>Controlled by construction.</strong> Declared scope only. Acceptance frozen before dispatch. Done comes from a verified receipt.</div><div class="submit"><button class="btn primary" type="submit">Create work item</button><button class="btn" type="button" id="clearForm">Clear</button></div></form></section>
<section class="panel board-panel"><div class="panel-head"><div><h2 class="panel-title">Work graph</h2><div class="kicker" id="boardKicker">Fresh sessions, bounded scope, durable receipts.</div></div><select class="filter" id="filter"><option value="all">All work</option><option value="active">Active only</option><option value="needs">Needs attention</option><option value="done">Completed</option></select></div><div class="board"><div class="lane"><div class="lane-head"><div class="lane-title">Ready</div><div class="count" id="countReady">0</div></div><div class="cards" id="laneReady"></div></div><div class="lane"><div class="lane-head"><div class="lane-title">Running</div><div class="count" id="countRunning">0</div></div><div class="cards" id="laneRunning"></div></div><div class="lane"><div class="lane-head"><div class="lane-title">Needs you</div><div class="count" id="countNeeds">0</div></div><div class="cards" id="laneNeeds"></div></div><div class="lane"><div class="lane-head"><div class="lane-title">Receipted</div><div class="count" id="countDone">0</div></div><div class="cards" id="laneDone"></div></div></div></section>
<aside class="panel inspector"><div class="panel-head"><div><h2 class="panel-title">Evidence inspector</h2><div class="kicker">Read the receipt, not the narration.</div></div><div class="repo" id="repoPill">—</div></div><div class="inspect-body" id="inspector"><div class="no-selection">Select a work card to inspect its specification, dependency state, live log, patch, and receipt.</div></div></aside></main></div>
<div class="toasts" id="toasts"></div><div class="modal-bg" id="settingsModal"><div class="modal"><div class="modal-head"><strong>Guardrails for unattended work</strong><button class="btn ghost" id="closeSettings">Close</button></div><form id="settingsForm"><div class="modal-body"><div class="row"><div class="field"><label>Concurrent workers</label><input id="maxWorkers" type="number" min="1" max="4"></div><div class="field"><label>Daily run limit</label><input id="dailyTasks" type="number" min="1" max="100"></div></div><div class="field"><label>Daily observed-cost limit, USD <span class="hint">0 disables</span></label><input id="dailyCost" type="number" min="0" max="100000" step=".01"></div><label class="check"><input id="stopOnFailure" type="checkbox"><span>Pause everything after a rejection or error.</span></label><p class="note">Cost stops use receipt telemetry already observed. The daily run limit remains the hard pre-dispatch bound when subscription window state is unavailable.</p></div><div class="modal-foot"><button class="btn" type="button" id="cancelSettings">Cancel</button><button class="btn primary">Save guardrails</button></div></form></div></div>
<script>__MONSTER_SCRIPT__</script></body></html>"""
