from __future__ import annotations

MARKUP = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#071016" id="themeMeta"><title>Tier Desk</title>
<script>(function(){var k="tier-desk-theme",v=localStorage.getItem(k),d=v||((window.matchMedia&&window.matchMedia("(prefers-color-scheme: light)").matches)?"light":"dark");document.documentElement.dataset.theme=d;document.documentElement.style.colorScheme=d})();</script>
<style>__MONSTER_STYLE__</style></head><body>
<div class="shell"><header class="topbar"><div class="brand"><div class="mark">T</div><div><h1>Tier Desk</h1><div class="sub" id="repoSub">Estate and evidence control · loading</div></div></div><nav class="desk-nav" aria-label="Tier Desk sections"><button class="nav-tab active" data-page="dashboard">Dashboard</button><button class="nav-tab" data-page="work">Work graph</button></nav><div class="actions"><div class="away"><span class="dot" id="awayDot"></span><span id="awayText">Safe to leave</span></div><button class="btn ghost theme-toggle" id="themeBtn" type="button" aria-label="Switch color theme"><span id="themeIcon">☼</span><span id="themeText">Light</span></button><button class="btn ghost work-control" id="settingsBtn">Guardrails</button><button class="btn warn work-control" id="pauseBtn">Pause after current</button><button class="btn danger work-control" id="stopBtn">Emergency stop</button></div></header>

<main class="dashboard-page page active" id="pageDashboard"><section class="dashboard-hero"><div><div class="eyebrow">Local estate · direct provider telemetry</div><h2>Your work, tanks, and loose ends.</h2><p>Every reading shows its source and observation time. Stale or failed collectors stay visible.</p></div><button class="btn primary refresh-dashboard" id="refreshDashboard">Refresh direct sources</button></section>
<section class="gauge-grid" id="gaugeGrid"><div class="dash-card loading-card">Reading Claude and Codex directly…</div></section>
<section class="estate-head"><div><div class="eyebrow">Local projects</div><h2>Estate</h2><div class="kicker" id="estateSummary">Discovering repositories and open queue work…</div></div><div class="estate-tools"><label class="sr-only" for="projectSearch">Search projects</label><input id="projectSearch" type="search" placeholder="Search project, branch, path…"><div class="filter-chips" aria-label="Project filters"><button class="chip active" data-project-filter="all" aria-pressed="true">All <span id="filterAllCount">0</span></button><button class="chip" data-project-filter="open" aria-pressed="false">Open <span id="filterOpenCount">0</span></button><button class="chip" data-project-filter="dirty" aria-pressed="false">Dirty <span id="filterDirtyCount">0</span></button></div></div></section>
<section class="project-grid" id="projectGrid"><div class="dash-card loading-card">Scanning local git state…</div></section></main>

<section class="work-page page" id="pageWork"><section class="metrics"><div class="metric"><div class="label">Scheduler</div><div class="value" id="mScheduler">—</div></div><div class="metric"><div class="label">Running</div><div class="value" id="mRunning">0</div></div><div class="metric"><div class="label">Ready</div><div class="value" id="mReady">0</div></div><div class="metric"><div class="label">Blocked</div><div class="value" id="mBlocked">0</div></div><div class="metric"><div class="label">Accepted</div><div class="value" id="mAccepted">0</div></div><div class="metric"><div class="label">Verified yield</div><div class="value" id="mYield">—</div></div><div class="metric"><div class="label">Today</div><div class="value" id="mToday">$0.00 <span class="small" id="mTodayTasks">0 runs</span></div></div></section>
<main class="workspace"><section class="panel intake-panel"><div class="panel-head"><div><h2 class="panel-title">Tell the desk</h2><div class="kicker">Describe the outcome. The desk prepares the packet.</div></div></div>
<form class="form intake-form" id="taskForm"><div class="field intent-field"><label for="intent">What should happen?</label><textarea id="intent" maxlength="12000" required placeholder="Make the work graph simple enough that I never need a manual to start useful work."></textarea><div class="intent-help">Use ordinary language. Mention constraints that matter; skip internal desk vocabulary.</div></div><div class="submit intake-submit"><button class="btn primary" type="submit" id="prepareWork">Prepare this work</button><button class="btn" type="button" id="clearForm">Clear</button></div>
<section class="plan-preview" id="planPreview" hidden aria-live="polite"><div class="plan-ready"><span class="plan-pulse"></span><div><strong>Ready for your decision</strong><span>The desk generated a bounded, testable work packet.</span></div></div><h3 id="planTitle">Work title</h3><div class="plan-facts"><div><span>Where it may work</span><strong id="planScope">Current project</strong><small id="planScopeWhy"></small></div><div><span>How done is proven</span><strong class="code" id="planProof"></strong><small id="planProofWhy"></small></div><div><span>Who handles it</span><strong id="planWorker">Ready worker</strong><small id="planWorkerWhy"></small></div></div><div class="route-head"><strong>How the desk gets it done</strong><span id="routeDoctrine"></span></div><div class="route-strip" id="routeStrip"></div><div class="decision-row"><button class="btn primary" id="startWork" type="button">Start guarded work</button><button class="btn" id="saveDraft" type="button">Keep as draft</button></div>
<details class="technical" id="technicalDetails"><summary>Change technical details</summary><p class="note">These are generated. Change them only when the desk guessed wrong.</p><div class="field"><label>Work title</label><input id="title" maxlength="160"></div><div class="field"><label>Project scope <span class="hint">one path or folder per line</span></label><textarea class="code" id="files"></textarea></div><div class="field"><label>Proof command <span class="hint">runs after the change</span></label><textarea class="code" id="acceptance"></textarea></div><div class="row"><div class="field"><label>Worker lane</label><select id="arm"><option>arm_b</option><option>arm_a</option><option>arm_c</option></select></div><div class="field"><label>Priority</label><input id="priority" type="number" min="0" max="100" value="50"></div></div><div class="field"><label>Wait for work IDs <span class="hint">optional</span></label><input class="code" id="depends"></div><details class="runtime-details"><summary>Runtime wiring</summary><div class="field"><label>Backend manifest <span class="hint">inside project</span></label><input class="code" id="manifest" value="pilot_backends.json"></div></details></details><div class="safety"><strong>Why this remains controlled:</strong> scope and proof are frozen before dispatch; completion still requires a verified receipt.</div></section></form></section>
<section class="panel board-panel"><div class="panel-head"><div><h2 class="panel-title">Work graph</h2><div class="kicker" id="boardKicker">Fresh sessions, bounded scope, durable receipts.</div></div><select class="filter" id="filter"><option value="all">All work</option><option value="active">Active</option><option value="needs">Needs attention</option><option value="done">Accepted</option></select></div><div class="board"><section class="lane"><div class="lane-head"><span class="lane-title">Ready</span><span class="count" id="countReady">0</span></div><div class="cards" id="laneReady"></div></section><section class="lane"><div class="lane-head"><span class="lane-title">Running</span><span class="count" id="countRunning">0</span></div><div class="cards" id="laneRunning"></div></section><section class="lane"><div class="lane-head"><span class="lane-title">Needs you</span><span class="count" id="countNeeds">0</span></div><div class="cards" id="laneNeeds"></div></section><section class="lane"><div class="lane-head"><span class="lane-title">Done</span><span class="count" id="countDone">0</span></div><div class="cards" id="laneDone"></div></section></div></section>
<aside class="panel inspector"><div class="panel-head"><div><h2 class="panel-title">Evidence inspector</h2><div class="kicker">Read the receipt, not the narration.</div></div><div class="repo" id="repoPill">—</div></div><div class="inspect-body" id="inspector"><div class="no-selection">Select a work card to inspect its specification, dependency state, live log, patch, and receipt.</div></div></aside></main></section></div>
<div class="toasts" id="toasts"></div><div class="modal-bg" id="settingsModal"><div class="modal"><div class="modal-head"><strong>Guardrails for unattended work</strong><button class="btn ghost" id="closeSettings">Close</button></div><form id="settingsForm"><div class="modal-body"><div class="row"><div class="field"><label>Concurrent workers</label><input id="maxWorkers" type="number" min="1" max="4"></div><div class="field"><label>Daily run limit</label><input id="dailyTasks" type="number" min="1" max="100"></div></div><div class="field"><label>Daily observed-cost limit, USD <span class="hint">0 disables</span></label><input id="dailyCost" type="number" min="0" max="100000" step=".01"></div><label class="check"><input id="stopOnFailure" type="checkbox"><span>Pause everything after a rejection or error.</span></label><p class="note">Cost stops use receipt telemetry already observed. The daily run limit remains the hard pre-dispatch bound when subscription window state is unavailable.</p></div><div class="modal-foot"><button class="btn" type="button" id="cancelSettings">Cancel</button><button class="btn primary">Save guardrails</button></div></form></div></div>
<script>__MONSTER_SCRIPT__</script></body></html>"""
