from __future__ import annotations

SCRIPT = r"""
const TOKEN="__TIER_DESK_TOKEN__",S={snap:null,selected:null,task:null};const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=v=>`$${Number(v||0).toFixed(2)}`;const compact=v=>{let n=Number(v||0);return n>=1e6?`${(n/1e6).toFixed(1)}m`:n>=1e3?`${(n/1e3).toFixed(1)}k`:String(n)};const when=v=>{if(!v)return"—";let d=new Date(v);return isNaN(d)?v:d.toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})};
function toast(m,k="ok"){let n=document.createElement("div");n.className=`toast ${k}`;n.textContent=m;$("toasts").append(n);setTimeout(()=>n.remove(),4500)}
async function api(path,opt={}){let o={...opt,headers:{...(opt.headers||{})}};if(o.method&&o.method!=="GET"){o.headers["Content-Type"]="application/json";o.headers["X-Tier-Desk-Token"]=TOKEN}let r=await fetch(path,o),t=await r.text(),d={};try{d=t?JSON.parse(t):{}}catch{d={ok:false,error:t||r.statusText}}if(!r.ok||d.ok===false)throw Error(d.error||r.statusText);return d}
const effective=t=>t.state==="QUEUED"&&t.blocked_by?.length?"BLOCKED":t.state;function lane(t){let s=effective(t);if(s==="RUNNING")return"running";if(s==="QUEUED")return"ready";if(["DRAFT","BLOCKED","REJECTED","ERROR","CANCELED","INTERRUPTED"].includes(s))return"needs";return"done"}function visible(t){let f=$("filter").value,l=lane(t);return f==="all"||(f==="active"&&["ready","running"].includes(l))||(f==="needs"&&l==="needs")||(f==="done"&&l==="done")}
function card(t){let r=t.last_run,s=effective(t),tok=r?Number(r.input_tokens||0)+Number(r.output_tokens||0):0,b=t.blocked_by?.map(x=>x.id).join(", ");return `<article class="card ${S.selected===t.id?"selected":""}" data-task="${esc(t.id)}"><div class="card-top"><div class="card-title">${esc(t.title)}</div><div class="priority">P${t.priority}</div></div><div class="state ${s}">${s}</div>${b?`<div class="blocked">Waiting on ${esc(b)}</div>`:""}<div class="meta"><span>${esc(t.arm)}</span><span>${r?money(r.cost_usd):"no run"}</span><span>${t.files.length} scope${t.files.length===1?"":"s"}</span><span>${tok?compact(tok)+" tok":when(t.created_at)}</span></div></article>`}
function renderBoard(){let tasks=(S.snap?.tasks||[]).filter(visible),g={ready:[],running:[],needs:[],done:[]};tasks.forEach(t=>g[lane(t)].push(t));for(let [name,list] of Object.entries(g)){let cap=name[0].toUpperCase()+name.slice(1);$(`count${cap}`).textContent=list.length;$(`lane${cap}`).innerHTML=list.length?list.map(card).join(""):`<div class="empty">Nothing here.</div>`}document.querySelectorAll("[data-task]").forEach(n=>n.onclick=()=>selectTask(n.dataset.task))}
function renderMetrics(){let x=S.snap,st=x.stats.states||{},blocked=x.tasks.filter(t=>effective(t)==="BLOCKED").length,p=x.settings.paused;$("mScheduler").textContent=p?"PAUSED":"ARMED";$("mScheduler").style.color=p?"var(--amber)":"var(--mint)";$("mRunning").textContent=st.RUNNING||0;$("mReady").textContent=Math.max(0,(st.QUEUED||0)-blocked);$("mBlocked").textContent=blocked;$("mAccepted").textContent=st.ACCEPTED||0;$("mYield").textContent=x.stats.success_rate==null?"—":`${Math.round(x.stats.success_rate*100)}%`;$("mToday").firstChild.textContent=`${money(x.stats.daily.cost_usd)} `;$("mTodayTasks").textContent=`${x.stats.daily.tasks} runs`;let safe=x.settings.stop_on_failure&&x.settings.daily_task_limit>0&&x.settings.max_workers===1;$("awayText").textContent=p?(x.settings.pause_reason||"Paused"):safe?"Safe to leave":"Review guardrails";$("awayDot").className=`dot ${p?"paused":safe?"":"danger"}`;$("pauseBtn").textContent=p?"Resume scheduling":"Pause after current";$("repoSub").textContent=`${p?"Paused":"Armed"} · ${x.repo}`;$("repoPill").textContent=x.repo;$("boardKicker").textContent=p?`No new work: ${x.settings.pause_reason||"operator pause"}`:`Fresh sessions · ${x.settings.max_workers} worker max · stop on failure ${x.settings.stop_on_failure?"on":"off"}`}
function arms(){let a=S.snap?.cartridges?.arms||{},names=Object.keys(a),sel=$("arm"),cur=sel.value;if(!names.length)return;sel.innerHTML=names.map(n=>`<option value="${esc(n)}">${esc(n)} · ${esc(a[n].model_id||"unknown")} · ${esc(a[n].cost_basis||"unknown cost")}</option>`).join("");if(names.includes(cur))sel.value=cur}
async function refresh(){try{let d=await api("/api/state");S.snap=d.state;renderMetrics();arms();renderBoard();if(S.selected)await selectTask(S.selected,true)}catch(e){toast(e.message,"error")}}
function buttons(t){let b=[],s=t.state,r=t.runs?.[0];if(s==="DRAFT")b.push(`<button class="btn primary" data-action="arm">Arm</button>`);if(s==="QUEUED")b.push(`<button class="btn" data-action="hold">Hold</button>`);if(["REJECTED","ERROR","CANCELED","INTERRUPTED"].includes(s))b.push(`<button class="btn primary" data-action="retry">Retry</button>`);if(s==="RUNNING")b.push(`<button class="btn danger" data-action="cancel">Cancel run</button>`);if(["DRAFT","QUEUED"].includes(s))b.push(`<button class="btn danger" data-action="cancel">Cancel</button>`);if(r?.receipt)b.push(`<button class="btn" data-download="receipt">Receipt</button>`);if(r&&["ACCEPTED","REJECTED"].includes(r.state))b.push(`<button class="btn" data-download="patch">Patch</button>`);return b.join("")}
function run(r){let tok=Number(r.input_tokens||0)+Number(r.output_tokens||0);return `<div class="run"><div class="run-top"><span class="state ${r.state}">${r.state}</span><span>attempt ${r.attempt}</span></div><div class="run-meta">${esc(when(r.started_at))}<br>${money(r.cost_usd)} · ${compact(tok)} tokens · exit ${esc(r.exit_code??"—")}</div></div>`}
async function selectTask(id,silent=false){S.selected=id;renderBoard();try{let d=await api(`/api/tasks/${encodeURIComponent(id)}`);S.task=d.task;inspect(d.task)}catch(e){if(!silent)toast(e.message,"error")}}
function inspect(t){let s=effective(t),deps=t.dependencies?.length?t.dependencies.map(d=>`${d.id} (${d.state})`).join(", "):"none",r=t.runs?.[0],ver=r?.verification?JSON.stringify(r.verification,null,2):"No verification result yet.";$("inspector").innerHTML=`<section class="section"><h3 class="inspect-title">${esc(t.title)}</h3><div class="id">${esc(t.id)}</div><div class="state ${s}">${s}</div><div class="inspect-actions">${buttons(t)}</div></section><section class="section"><div class="section-label">Control envelope</div><dl class="definition"><div><dt>Cartridge</dt><dd>${esc(t.arm)}</dd></div><div><dt>Priority</dt><dd>${t.priority}</dd></div><div><dt>Dependencies</dt><dd>${esc(deps)}</dd></div><div><dt>Allowed scope</dt><dd>${t.files.map(esc).join("<br>")}</dd></div><div><dt>Manifest</dt><dd>${esc(t.manifest)}</dd></div></dl></section><section class="section"><div class="section-label">Task</div><pre class="codebox">${esc(t.task)}</pre></section><section class="section"><div class="section-label">Frozen acceptance</div><pre class="codebox">${esc(t.acceptance)}</pre></section><section class="section"><div class="section-label">Live log</div><pre class="codebox logbox" id="liveLog">${r?"Loading…":"No run has started."}</pre></section><section class="section"><div class="section-label">Verification</div><pre class="codebox">${esc(ver)}</pre></section><section class="section"><div class="section-label">Attempts</div>${t.runs?.length?t.runs.map(run).join(""):`<div class="note">No attempts yet.</div>`}</section>`;document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>taskAction(t.id,b.dataset.action));document.querySelectorAll("[data-download]").forEach(b=>b.onclick=()=>download(t,b.dataset.download));if(r)loadLog(r.id)}
async function loadLog(id){let box=$("liveLog");if(!box)return;try{let r=await fetch(`/api/runs/${encodeURIComponent(id)}/log?tail=120000`);box.textContent=await r.text()||"No output yet.";box.scrollTop=box.scrollHeight}catch(e){box.textContent=e.message}}
async function taskAction(id,a){if(a==="cancel"&&!confirm("Cancel this work item? A running process will be terminated."))return;try{await api(`/api/tasks/${encodeURIComponent(id)}/${a}`,{method:"POST",body:"{}"});toast(`${id}: ${a} recorded`);await refresh()}catch(e){toast(e.message,"error")}}
function download(t,k){let r=t.runs?.[0];if(r)window.open(`/api/runs/${encodeURIComponent(r.id)}/${k}`,"_blank","noopener")}
$("taskForm").onsubmit=async e=>{e.preventDefault();let p={title:$("title").value,task:$("task").value,files:$("files").value,acceptance:$("acceptance").value,arm:$("arm").value,priority:Number($("priority").value),depends_on:$("depends").value,manifest:$("manifest").value,queue_now:$("queueNow").checked,approval_required:$("approvalRequired").checked};try{let d=await api("/api/tasks",{method:"POST",body:JSON.stringify(p)});toast(`${d.task.id} created`);for(let id of ["title","task","files","acceptance","depends"])$(id).value="";await refresh();await selectTask(d.task.id,true)}catch(e){toast(e.message,"error")}};$("clearForm").onclick=()=>$("taskForm").reset();$("filter").onchange=renderBoard;
$("pauseBtn").onclick=async()=>{try{if(S.snap.settings.paused)await api("/api/control/resume",{method:"POST",body:"{}"});else await api("/api/control/pause",{method:"POST",body:JSON.stringify({reason:"operator paused scheduling"})});await refresh()}catch(e){toast(e.message,"error")}};$("stopBtn").onclick=async()=>{if(!confirm("Emergency stop pauses scheduling and terminates every active run. Continue?"))return;try{await api("/api/control/emergency-stop",{method:"POST",body:"{}"});toast("Emergency stop recorded","error");await refresh()}catch(e){toast(e.message,"error")}};
function openSettings(){let s=S.snap.settings;$("maxWorkers").value=s.max_workers;$("dailyTasks").value=s.daily_task_limit;$("dailyCost").value=s.daily_cost_limit_usd;$("stopOnFailure").checked=s.stop_on_failure;$("settingsModal").classList.add("open")}function closeSettings(){$("settingsModal").classList.remove("open")}$("settingsBtn").onclick=openSettings;$("closeSettings").onclick=closeSettings;$("cancelSettings").onclick=closeSettings;$("settingsModal").onclick=e=>{if(e.target===$("settingsModal"))closeSettings()};$("settingsForm").onsubmit=async e=>{e.preventDefault();let p={max_workers:Number($("maxWorkers").value),daily_task_limit:Number($("dailyTasks").value),daily_cost_limit_usd:Number($("dailyCost").value),stop_on_failure:$("stopOnFailure").checked};try{await api("/api/settings",{method:"POST",body:JSON.stringify(p)});closeSettings();toast("Guardrails saved");await refresh()}catch(e){toast(e.message,"error")}};
refresh();setInterval(()=>refresh(),1800);
"""
